builds:
- id: ghcr-cleanup
  main: ./
  binary: ghcr-cleanup
  env:
  - CGO_ENABLED=0
  ldflags:
  - "-s -w -X github.com/rajatjindal/ghcr-cleanup/cmd.Version={{.Version}}"
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64

archives:
- builds:
  - ghcr-cleanup
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  files:
  - LICENSE
